### ISSUE TITLE
Launch Failure

### ISSUE THREAD

**Issue by SolarAquarion** [PathToLife/Nyaa.si-Downloader#1]
```
Created window "Site Parser Downloader" 1000x650 x:460.0 y:215.0
/home/solaraquarion/Nyaa.si-Downloader/icon/SiteParserDownloader_Icon.ico
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    app = App()
  File "main.py", line 18, in __init__
    root.window.iconbitmap(self.resource_path('icon/SiteParserDownloader_Icon.ico'))
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1868, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/solaraquarion/Nyaa.si-Downloader/icon/SiteParserDownloader_Icon.ico" not defined
```

**Comment by PathToLife** [comment]
Sorry, app wasn't ready for release back then, should be up and running now.
